// ./src/pipeline/generated.c
/* Auto-generated by codegen/generate_pipeline.py — do not edit */
#include <stdint.h>
#include <stdlib.h>
#include "pipeline/jump_table.h"
#include "core/opcodes.h"
#include "pipeline/job.h"
#include "pipeline/generated.h"

#ifndef IMGENGINE_GENERATED_PIPELINES
#define IMGENGINE_GENERATED_PIPELINES

void pipeline_photo_6x6(img_ctx_t *ctx, img_buffer_t *buf, void *params) {
    (void)ctx;
    (void)buf;
    (void)params;
    /* auto-generated pipeline: photo_6x6 */
    /* Pipeline body (DSL):
resize(4096,4096)
    crop(6,6)
    border(2)
    padding(20)
    */
}

void pipeline_photo_6x3(img_ctx_t *ctx, img_buffer_t *buf, void *params) {
    (void)ctx;
    (void)buf;
    (void)params;
    /* auto-generated pipeline: photo_6x3 */
    /* Pipeline body (DSL):
resize(4096,4096)
    crop(6,3)
    border(2)
    padding(20)
    */
}

void pipeline_photo_6x1(img_ctx_t *ctx, img_buffer_t *buf, void *params) {
    (void)ctx;
    (void)buf;
    (void)params;
    /* auto-generated pipeline: photo_6x1 */
    /* Pipeline body (DSL):
resize(4096,4096)
    crop(6,1)
    border(2)
    padding(20)
    */
}

void pipeline_passport_45x35(img_ctx_t *ctx, img_buffer_t *buf, void *params) {
    (void)ctx;
    (void)buf;
    (void)params;
    /* auto-generated pipeline: passport_45x35 */
    /* Pipeline body (DSL):
resize(4096,4096)
    crop(6,6)
    border(2)
    padding(20)
    */
}

void pipeline_printready_6x6(img_ctx_t *ctx, img_buffer_t *buf, void *params) {
    (void)ctx;
    (void)buf;
    (void)params;
    /* auto-generated pipeline: printready_6x6 */
    /* Pipeline body (DSL):
resize(4096,4096)
    crop(6,6)
    border(2)
    padding(20)
    */
}

/*
 * Explicit registration function.
 * Call from deterministic startup (img_api_init / engine init).
 */
void register_generated_pipelines(void) {
    img_register_op((OP_CUSTOM_BASE + 0), (img_op_fn)pipeline_photo_6x6, NULL);
    img_register_op((OP_CUSTOM_BASE + 1), (img_op_fn)pipeline_photo_6x3, NULL);
    img_register_op((OP_CUSTOM_BASE + 2), (img_op_fn)pipeline_photo_6x1, NULL);
    img_register_op((OP_CUSTOM_BASE + 3), (img_op_fn)pipeline_passport_45x35, NULL);
    img_register_op((OP_CUSTOM_BASE + 4), (img_op_fn)pipeline_printready_6x6, NULL);
}

#endif /* IMGENGINE_GENERATED_PIPELINES */
