# infra/docker-compose.yaml
services:


  api:
    build: ../api-service
    ports:
      - "8000:8000"
    volumes:
      - ../data:/data
    depends_on:
      - redis
      - db

  worker:
    build:
      context: ..
      dockerfile: worker-service/Dockerfile
    # command: celery -A tasks worker --loglevel=info
    command: uv run celery -A tasks worker --loglevel=info
    volumes:
      - ../data:/data
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: imgengine
      POSTGRES_PASSWORD: imgengine
      POSTGRES_DB: imgengine